### ISSUE TITLE
SDNumber function

### ISSUE THREAD

**Issue by rfabbri9** [CatiVich/STDF-network#1]
SDNumber (NetworkSTDall.m file, lines 192, 199, 206) not defined/missing.
Is it a kind of random number generator for having a different value of SD for every neuron?

**Comment by CatiVich** [comment]
Yes, sorry. The file is missing. I will upload it in the following days

Thanks to inform me about it.

Best,
Cati.

**Comment by CatiVich** [comment]
File is already uploaded. 

Best,
Cati.

**Comment by rfabbri9** [comment]
Thank you very much for providing the file!
